### ISSUE TITLE
Parse User Input Compiler-Style

### ISSUE THREAD

**Issue by dns2utf8** [coredump-ch/coredumpbot#10]

**Comment by dbrgn** [comment]
There are a few parser generator libraries around. Can you make the commands into a LR(1) syntax? This one looks interesting, for example: https://github.com/nikomatsakis/lalrpop

**Comment by dns2utf8** [comment]
Looked very good, but it is not compiling after a Day of Work. Working with pure Rust for now.

**Comment by dns2utf8** [comment]
Implemented.
