### ISSUE TITLE
Cache /crowd

### ISSUE THREAD

**Issue by dns2utf8** [coredump-ch/coredumpbot#2]
Since it updates once per Minute.

**Comment by dbrgn** [comment]
Don't assume that it updates once per minute. That's only the current situation, but it might change (e.g. as soon as we update the status switches to use the new SpaceAPI implementation with event driven API).

The value is already cached in the SpaceAPI. No need to cache the results again.

**Comment by dns2utf8** [comment]
Currently the api takes up to 53 seconds to respond. So a cache for a minute would reduce the load, because right now it has to fetch the information for every user again.

Plus the information may be fresh inside the bot if #5 is implemented.

**Comment by dbrgn** [comment]
That will improve a lot. Wait with caching until we deployed the new SpaceAPI version.

**Comment by dns2utf8** [comment]
obsolete
